version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 10
    labels:
      - dependencies
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      nest:
        patterns:
          - "@nestjs/*"
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - ci
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - docker
